title: "Dark Market"
tagline: "Fill or Kill"
description: "A Publication Dedicated to Underground Economies"
baseurl: "/darkmarket.io"
url: "darkmarket.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

font-size: small
