title: "Dark Market"
tagline: "Fill or Kill"
description: "A Publication Dedicated to Underground Economies"
github_username: Stormzer0
baseurl: "/darkmarket.io"
url: "darkmarket.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
